# Generated by Django 4.1.5 on 2023-01-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='entries',
        ),
    ]
