# Generated by Django 4.1.5 on 2023-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='entry',
        ),
    ]
