# Generated by Django 4.1.5 on 2023-01-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
